/*
 * Copyright 2018 Lithium Technologies Pvt Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lithium.community.android.sdk.notification;

import android.content.Context;

import lithium.community.android.sdk.exception.LiRestResponseException;

/**
 * Notification Provider Interface. Implementor class LiNotificationProviderImpl.
 * Created by shoureya.kant on 12/28/16.
 */

public interface LiNotificationProvider {

    /**
     * This method is use to update device id with the new one generated by the push notification providers.
     * This method will be called periodically.
     *
     * @param deviceId It is device id.
     * @throws LiRestResponseException {@link LiRestResponseException}
     */
    void onIdRefresh(String deviceId, Context context) throws LiRestResponseException;
}
