/*
 * NotificationProvider.java
 * Created on Dec 28, 2016
 *
 * Copyright 2016 Lithium Technologies, Inc.
 * San Francisco, California, U.S.A.  All Rights Reserved.
 *
 * This software is the  confidential and proprietary information
 * of  Lithium  Technologies,  Inc.  ("Confidential Information")
 * You shall not disclose such Confidential Information and shall
 * use  it  only in  accordance  with  the terms of  the  license
 * agreement you entered into with Lithium.
 */

package lithium.community.android.sdk.notification;

import android.content.Context;

import lithium.community.android.sdk.exception.LiRestResponseException;

/**
 * Notification Provider Interface. Implementor class LiNotificationProviderImpl.
 * Created by shoureya.kant on 12/28/16.
 */

public interface LiNotificationProvider {

    /**
     * This method is use to update device id with the new one generated by the push notification providers.
     * This method will be called periodically.
     * @param deviceId It is device id.
     * @param liPushNotificationProvider {@link LiPushNotificationProvider}
     * @throws LiRestResponseException {@link LiRestResponseException}
     */
    void onIdRefresh(String deviceId, LiPushNotificationProvider liPushNotificationProvider, Context context) throws LiRestResponseException;
}
